package com.create80.rd.modules.contract.api.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class ContractBillInvoicing implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.id
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.contract_id
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private String contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.sn
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private String sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.name
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.condition
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private String condition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.bill_invoicing
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private BigDecimal billInvoicing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.bill_invoicing_date
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private Date billInvoicingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.insert_by
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private String insertBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.update_by
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.insert_time
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.update_time
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.keep_notification
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private Boolean keepNotification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.is_deleted
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private String isDeleted;

    private List<ContractBillInvoiced> contractBillInvoicedList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ecm_contract_bill_invoicing
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.id
     *
     * @return the value of ecm_contract_bill_invoicing.id
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.id
     *
     * @param id the value for ecm_contract_bill_invoicing.id
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.contract_id
     *
     * @return the value of ecm_contract_bill_invoicing.contract_id
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.contract_id
     *
     * @param contractId the value for ecm_contract_bill_invoicing.contract_id
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.sn
     *
     * @return the value of ecm_contract_bill_invoicing.sn
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.sn
     *
     * @param sn the value for ecm_contract_bill_invoicing.sn
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setSn(String sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.name
     *
     * @return the value of ecm_contract_bill_invoicing.name
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.name
     *
     * @param name the value for ecm_contract_bill_invoicing.name
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.condition
     *
     * @return the value of ecm_contract_bill_invoicing.condition
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.condition
     *
     * @param condition the value for ecm_contract_bill_invoicing.condition
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setCondition(String condition) {
        this.condition = condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.bill_invoicing
     *
     * @return the value of ecm_contract_bill_invoicing.bill_invoicing
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public BigDecimal getBillInvoicing() {
        return billInvoicing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.bill_invoicing
     *
     * @param billInvoicing the value for ecm_contract_bill_invoicing.bill_invoicing
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setBillInvoicing(BigDecimal billInvoicing) {
        this.billInvoicing = billInvoicing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.bill_invoicing_date
     *
     * @return the value of ecm_contract_bill_invoicing.bill_invoicing_date
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public Date getBillInvoicingDate() {
        return billInvoicingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.bill_invoicing_date
     *
     * @param billInvoicingDate the value for ecm_contract_bill_invoicing.bill_invoicing_date
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setBillInvoicingDate(Date billInvoicingDate) {
        this.billInvoicingDate = billInvoicingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.insert_by
     *
     * @return the value of ecm_contract_bill_invoicing.insert_by
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public String getInsertBy() {
        return insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.insert_by
     *
     * @param insertBy the value for ecm_contract_bill_invoicing.insert_by
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setInsertBy(String insertBy) {
        this.insertBy = insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.update_by
     *
     * @return the value of ecm_contract_bill_invoicing.update_by
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.update_by
     *
     * @param updateBy the value for ecm_contract_bill_invoicing.update_by
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.insert_time
     *
     * @return the value of ecm_contract_bill_invoicing.insert_time
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.insert_time
     *
     * @param insertTime the value for ecm_contract_bill_invoicing.insert_time
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.update_time
     *
     * @return the value of ecm_contract_bill_invoicing.update_time
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.update_time
     *
     * @param updateTime the value for ecm_contract_bill_invoicing.update_time
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.keep_notification
     *
     * @return the value of ecm_contract_bill_invoicing.keep_notification
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public Boolean getKeepNotification() {
        return keepNotification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.keep_notification
     *
     * @param keepNotification the value for ecm_contract_bill_invoicing.keep_notification
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setKeepNotification(Boolean keepNotification) {
        this.keepNotification = keepNotification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.is_deleted
     *
     * @return the value of ecm_contract_bill_invoicing.is_deleted
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.is_deleted
     *
     * @param isDeleted the value for ecm_contract_bill_invoicing.is_deleted
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    public List<ContractBillInvoiced> getContractBillInvoicedList() {
        return contractBillInvoicedList;
    }

    public void setContractBillInvoicedList(List<ContractBillInvoiced> contractBillInvoicedList) {
        this.contractBillInvoicedList=contractBillInvoicedList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecm_contract_bill_invoicing
     *
     * @mbg.generated Thu Jun 21 09:54:11 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", contractId=").append(contractId);
        sb.append(", sn=").append(sn);
        sb.append(", name=").append(name);
        sb.append(", condition=").append(condition);
        sb.append(", billInvoicing=").append(billInvoicing);
        sb.append(", billInvoicingDate=").append(billInvoicingDate);
        sb.append(", insertBy=").append(insertBy);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", keepNotification=").append(keepNotification);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", contractBillInvoicedList=").append(contractBillInvoicedList);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}