package com.create80.rd.modules.contract.api.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class ContractAccountsReceivable implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.id
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.contract_id
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private String contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.sn
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private String sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.name
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.condition
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private String condition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.accounts_receivable
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private BigDecimal accountsReceivable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.accounts_receivable_percent
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private Integer accountsReceivablePercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.accounts_receivable_method
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private String accountsReceivableMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.accounts_receivable_date
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private Date accountsReceivableDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.keep_notification
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private Boolean keepNotification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.insert_by
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private String insertBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.update_by
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.insert_time
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.update_time
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_accounts_receivable.is_deleted
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private String isDeleted;

    private List<ContractAccountsReceived> contractAccountsReceivedList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ecm_contract_accounts_receivable
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.id
     *
     * @return the value of ecm_contract_accounts_receivable.id
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.id
     *
     * @param id the value for ecm_contract_accounts_receivable.id
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.contract_id
     *
     * @return the value of ecm_contract_accounts_receivable.contract_id
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.contract_id
     *
     * @param contractId the value for ecm_contract_accounts_receivable.contract_id
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.sn
     *
     * @return the value of ecm_contract_accounts_receivable.sn
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.sn
     *
     * @param sn the value for ecm_contract_accounts_receivable.sn
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setSn(String sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.name
     *
     * @return the value of ecm_contract_accounts_receivable.name
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.name
     *
     * @param name the value for ecm_contract_accounts_receivable.name
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.condition
     *
     * @return the value of ecm_contract_accounts_receivable.condition
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.condition
     *
     * @param condition the value for ecm_contract_accounts_receivable.condition
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setCondition(String condition) {
        this.condition = condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.accounts_receivable
     *
     * @return the value of ecm_contract_accounts_receivable.accounts_receivable
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public BigDecimal getAccountsReceivable() {
        return accountsReceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.accounts_receivable
     *
     * @param accountsReceivable the value for ecm_contract_accounts_receivable.accounts_receivable
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setAccountsReceivable(BigDecimal accountsReceivable) {
        this.accountsReceivable = accountsReceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.accounts_receivable_percent
     *
     * @return the value of ecm_contract_accounts_receivable.accounts_receivable_percent
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public Integer getAccountsReceivablePercent() {
        return accountsReceivablePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.accounts_receivable_percent
     *
     * @param accountsReceivablePercent the value for ecm_contract_accounts_receivable.accounts_receivable_percent
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setAccountsReceivablePercent(Integer accountsReceivablePercent) {
        this.accountsReceivablePercent = accountsReceivablePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.accounts_receivable_method
     *
     * @return the value of ecm_contract_accounts_receivable.accounts_receivable_method
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public String getAccountsReceivableMethod() {
        return accountsReceivableMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.accounts_receivable_method
     *
     * @param accountsReceivableMethod the value for ecm_contract_accounts_receivable.accounts_receivable_method
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setAccountsReceivableMethod(String accountsReceivableMethod) {
        this.accountsReceivableMethod = accountsReceivableMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.accounts_receivable_date
     *
     * @return the value of ecm_contract_accounts_receivable.accounts_receivable_date
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public Date getAccountsReceivableDate() {
        return accountsReceivableDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.accounts_receivable_date
     *
     * @param accountsReceivableDate the value for ecm_contract_accounts_receivable.accounts_receivable_date
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setAccountsReceivableDate(Date accountsReceivableDate) {
        this.accountsReceivableDate = accountsReceivableDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.keep_notification
     *
     * @return the value of ecm_contract_accounts_receivable.keep_notification
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public Boolean getKeepNotification() {
        return keepNotification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.keep_notification
     *
     * @param keepNotification the value for ecm_contract_accounts_receivable.keep_notification
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setKeepNotification(Boolean keepNotification) {
        this.keepNotification = keepNotification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.insert_by
     *
     * @return the value of ecm_contract_accounts_receivable.insert_by
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public String getInsertBy() {
        return insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.insert_by
     *
     * @param insertBy the value for ecm_contract_accounts_receivable.insert_by
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setInsertBy(String insertBy) {
        this.insertBy = insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.update_by
     *
     * @return the value of ecm_contract_accounts_receivable.update_by
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.update_by
     *
     * @param updateBy the value for ecm_contract_accounts_receivable.update_by
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.insert_time
     *
     * @return the value of ecm_contract_accounts_receivable.insert_time
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.insert_time
     *
     * @param insertTime the value for ecm_contract_accounts_receivable.insert_time
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.update_time
     *
     * @return the value of ecm_contract_accounts_receivable.update_time
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.update_time
     *
     * @param updateTime the value for ecm_contract_accounts_receivable.update_time
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_accounts_receivable.is_deleted
     *
     * @return the value of ecm_contract_accounts_receivable.is_deleted
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_accounts_receivable.is_deleted
     *
     * @param isDeleted the value for ecm_contract_accounts_receivable.is_deleted
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    public List<ContractAccountsReceived> getContractAccountsReceivedList() {
        return contractAccountsReceivedList;
    }

    public void setContractAccountsReceivedList(List<ContractAccountsReceived> contractAccountsReceivedList) {
        this.contractAccountsReceivedList=contractAccountsReceivedList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecm_contract_accounts_receivable
     *
     * @mbg.generated Thu Jun 21 09:54:05 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", contractId=").append(contractId);
        sb.append(", sn=").append(sn);
        sb.append(", name=").append(name);
        sb.append(", condition=").append(condition);
        sb.append(", accountsReceivable=").append(accountsReceivable);
        sb.append(", accountsReceivablePercent=").append(accountsReceivablePercent);
        sb.append(", accountsReceivableMethod=").append(accountsReceivableMethod);
        sb.append(", accountsReceivableDate=").append(accountsReceivableDate);
        sb.append(", keepNotification=").append(keepNotification);
        sb.append(", insertBy=").append(insertBy);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", contractAccountsReceivedList=").append(contractAccountsReceivedList);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}