package com.create80.rd.modules.contract.api.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class ContractBillInvoicing implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.id
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.contract_id
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private String contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.sn
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private String sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.name
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.condition
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private String condition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.bill_invoicing
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private BigDecimal billInvoicing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.bill_invoicing_date
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private Date billInvoicingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.create_by
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.update_by
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.create_date
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.update_date
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.keep_notification
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private Boolean keepNotification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecm_contract_bill_invoicing.del_flag
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private String delFlag;

    private List<ContractBillInvoiced> contractBillInvoicedList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ecm_contract_bill_invoicing
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.id
     *
     * @return the value of ecm_contract_bill_invoicing.id
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.id
     *
     * @param id the value for ecm_contract_bill_invoicing.id
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.contract_id
     *
     * @return the value of ecm_contract_bill_invoicing.contract_id
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.contract_id
     *
     * @param contractId the value for ecm_contract_bill_invoicing.contract_id
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.sn
     *
     * @return the value of ecm_contract_bill_invoicing.sn
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.sn
     *
     * @param sn the value for ecm_contract_bill_invoicing.sn
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setSn(String sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.name
     *
     * @return the value of ecm_contract_bill_invoicing.name
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.name
     *
     * @param name the value for ecm_contract_bill_invoicing.name
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.condition
     *
     * @return the value of ecm_contract_bill_invoicing.condition
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.condition
     *
     * @param condition the value for ecm_contract_bill_invoicing.condition
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setCondition(String condition) {
        this.condition = condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.bill_invoicing
     *
     * @return the value of ecm_contract_bill_invoicing.bill_invoicing
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public BigDecimal getBillInvoicing() {
        return billInvoicing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.bill_invoicing
     *
     * @param billInvoicing the value for ecm_contract_bill_invoicing.bill_invoicing
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setBillInvoicing(BigDecimal billInvoicing) {
        this.billInvoicing = billInvoicing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.bill_invoicing_date
     *
     * @return the value of ecm_contract_bill_invoicing.bill_invoicing_date
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public Date getBillInvoicingDate() {
        return billInvoicingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.bill_invoicing_date
     *
     * @param billInvoicingDate the value for ecm_contract_bill_invoicing.bill_invoicing_date
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setBillInvoicingDate(Date billInvoicingDate) {
        this.billInvoicingDate = billInvoicingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.create_by
     *
     * @return the value of ecm_contract_bill_invoicing.create_by
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.create_by
     *
     * @param createBy the value for ecm_contract_bill_invoicing.create_by
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.update_by
     *
     * @return the value of ecm_contract_bill_invoicing.update_by
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.update_by
     *
     * @param updateBy the value for ecm_contract_bill_invoicing.update_by
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.create_date
     *
     * @return the value of ecm_contract_bill_invoicing.create_date
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.create_date
     *
     * @param createDate the value for ecm_contract_bill_invoicing.create_date
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.update_date
     *
     * @return the value of ecm_contract_bill_invoicing.update_date
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.update_date
     *
     * @param updateDate the value for ecm_contract_bill_invoicing.update_date
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.keep_notification
     *
     * @return the value of ecm_contract_bill_invoicing.keep_notification
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public Boolean getKeepNotification() {
        return keepNotification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.keep_notification
     *
     * @param keepNotification the value for ecm_contract_bill_invoicing.keep_notification
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setKeepNotification(Boolean keepNotification) {
        this.keepNotification = keepNotification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecm_contract_bill_invoicing.del_flag
     *
     * @return the value of ecm_contract_bill_invoicing.del_flag
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecm_contract_bill_invoicing.del_flag
     *
     * @param delFlag the value for ecm_contract_bill_invoicing.del_flag
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    public List<ContractBillInvoiced> getContractBillInvoicedList() {
        return contractBillInvoicedList;
    }

    public void setContractBillInvoicedList(List<ContractBillInvoiced> contractBillInvoicedList) {
        this.contractBillInvoicedList=contractBillInvoicedList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecm_contract_bill_invoicing
     *
     * @mbg.generated Thu May 31 11:02:52 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", contractId=").append(contractId);
        sb.append(", sn=").append(sn);
        sb.append(", name=").append(name);
        sb.append(", condition=").append(condition);
        sb.append(", billInvoicing=").append(billInvoicing);
        sb.append(", billInvoicingDate=").append(billInvoicingDate);
        sb.append(", createBy=").append(createBy);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", keepNotification=").append(keepNotification);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", contractBillInvoicedList=").append(contractBillInvoicedList);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}