variables:
  DEPLOY_HOME: /root/apache-tomcat-7.0.88
  APPLICATION_NAME: ra-operations-management
stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  script: make build dependencies

job 2:
  stage: build
  script: make build artifacts

job 3:
  stage: test
  script: make test

job 4:
  stage: deploy
  script: make deploy

