variables:
  DEPLOY_HOME: /root/apache-tomcat-7.0.88
  APPLICATION_NAME: ra-operations-management
stages:
  - build
  - destroy
  - deploy

job 1:
  tags:
      - 194
  stage: build
  script:
    - mvn clean install

job 3:
  stage: destroy
  script: make test

job 4:
  stage: deploy
  script: make deploy

