variables:
  SERVICE_NAME: ra-service-user-group
stages:
  - build
  - destroy
  - deploy
build-job:
  tags:
      - swarm
  stage: build
  script:
    - docker-compose build --force-rm
    - docker login -u admin -p admin123 192.168.1.182:9002
    - docker push 192.168.1.182:9002/$SERVICE_NAME:latest
destroy-job:
  tags:
      - swarm
  stage: destroy
  script:
    - docker stack rm $SERVICE_NAME
  allow_failure: true
deploy-job:
  tags:
    - swarm
  stage: deploy
  only:
    - master
  script:
    - env $(cat .env | xargs) docker stack deploy -c docker-compose.yml --with-registry-auth $SERVICE_NAME
