variables:
  DEPLOY_HOME: /home/gitlab-runner/apache-tomcat-7.0.88
  APPLICATION_NAME: ra-operations-management
stages:
  - deploy
deploy-job:
  tags:
      - '194'
  stage: deploy
  script:
    - mvn clean package
    - ll target
    - $DEPLOY_HOME/bin/shutdown.sh
    - rm -rf $DEPLOY_HOME/webapp/ra-operations-management*
    - ll target
    - cp target/ra-operations-management.war $DEPLOY_HOME/webapp/
    - ll target
    - $DEPLOY_HOME/bin/startup.sh
