variables:
  DEPLOY_HOME: /root/apache-tomcat-7.0.88
  APPLICATION_NAME: ra-operations-management
stages:
  - build
  - destroy
  - deploy
build-job:
  tags:
      - '194'
  stage: build
  script:
    - mvn clean install
destroy-job:
  tags:
      - '194'
  stage: destroy
  script:
    - expect su -c '$DEPLOY_HOME/bin/shutdown.sh' {send '123456'}
  allow_failure: true
deploy-job:
  tags:
      - '194'
  stage: deploy
  script:
    - su -c '$DEPLOY_HOME/bin/shutdown.sh'
    - su -c 'rm -rf $DEPLOY_HOME/webapp/ra-operations-management*'
    - su -c 'cp ra-operations-management.war $DEPLOY_HOME/webapp/'
    - su -c '$DEPLOY_HOME/bin/startup.sh'
