package com.create80.rd.modules.group.api.model;

import java.io.Serializable;
import java.util.Date;

public class SysUserGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.id
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.group_id
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.user_id
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.insert_by
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    private String insertBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.insert_time
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.update_by
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.update_time
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.remarks
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.is_deleted
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    private String isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_group.group_role
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    private String groupRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_group
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.id
     *
     * @return the value of sys_user_group.id
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.id
     *
     * @param id the value for sys_user_group.id
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.group_id
     *
     * @return the value of sys_user_group.group_id
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.group_id
     *
     * @param groupId the value for sys_user_group.group_id
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.user_id
     *
     * @return the value of sys_user_group.user_id
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.user_id
     *
     * @param userId the value for sys_user_group.user_id
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.insert_by
     *
     * @return the value of sys_user_group.insert_by
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public String getInsertBy() {
        return insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.insert_by
     *
     * @param insertBy the value for sys_user_group.insert_by
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public void setInsertBy(String insertBy) {
        this.insertBy = insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.insert_time
     *
     * @return the value of sys_user_group.insert_time
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.insert_time
     *
     * @param insertTime the value for sys_user_group.insert_time
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.update_by
     *
     * @return the value of sys_user_group.update_by
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.update_by
     *
     * @param updateBy the value for sys_user_group.update_by
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.update_time
     *
     * @return the value of sys_user_group.update_time
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.update_time
     *
     * @param updateTime the value for sys_user_group.update_time
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.remarks
     *
     * @return the value of sys_user_group.remarks
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.remarks
     *
     * @param remarks the value for sys_user_group.remarks
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.is_deleted
     *
     * @return the value of sys_user_group.is_deleted
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.is_deleted
     *
     * @param isDeleted the value for sys_user_group.is_deleted
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_group.group_role
     *
     * @return the value of sys_user_group.group_role
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public String getGroupRole() {
        return groupRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_group.group_role
     *
     * @param groupRole the value for sys_user_group.group_role
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    public void setGroupRole(String groupRole) {
        this.groupRole = groupRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_group
     *
     * @mbg.generated Wed Jun 20 13:15:57 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", groupId=").append(groupId);
        sb.append(", userId=").append(userId);
        sb.append(", insertBy=").append(insertBy);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remarks=").append(remarks);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", groupRole=").append(groupRole);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}