package com.create80.rd.modules.projectmanager.api.model;

import java.io.Serializable;
import java.util.Date;

public class ProjectContactRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contact_relation.id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contact_relation.project_id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contact_relation.contact_id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String contactId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contact_relation.insert_by
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String insertBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contact_relation.insert_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contact_relation.update_by
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contact_relation.update_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contact_relation.remarks
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contact_relation.is_deleted
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_contact_relation
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contact_relation.id
     *
     * @return the value of project_contact_relation.id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contact_relation.id
     *
     * @param id the value for project_contact_relation.id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contact_relation.project_id
     *
     * @return the value of project_contact_relation.project_id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contact_relation.project_id
     *
     * @param projectId the value for project_contact_relation.project_id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contact_relation.contact_id
     *
     * @return the value of project_contact_relation.contact_id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contact_relation.contact_id
     *
     * @param contactId the value for project_contact_relation.contact_id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setContactId(String contactId) {
        this.contactId = contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contact_relation.insert_by
     *
     * @return the value of project_contact_relation.insert_by
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getInsertBy() {
        return insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contact_relation.insert_by
     *
     * @param insertBy the value for project_contact_relation.insert_by
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setInsertBy(String insertBy) {
        this.insertBy = insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contact_relation.insert_time
     *
     * @return the value of project_contact_relation.insert_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contact_relation.insert_time
     *
     * @param insertTime the value for project_contact_relation.insert_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contact_relation.update_by
     *
     * @return the value of project_contact_relation.update_by
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contact_relation.update_by
     *
     * @param updateBy the value for project_contact_relation.update_by
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contact_relation.update_time
     *
     * @return the value of project_contact_relation.update_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contact_relation.update_time
     *
     * @param updateTime the value for project_contact_relation.update_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contact_relation.remarks
     *
     * @return the value of project_contact_relation.remarks
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contact_relation.remarks
     *
     * @param remarks the value for project_contact_relation.remarks
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contact_relation.is_deleted
     *
     * @return the value of project_contact_relation.is_deleted
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contact_relation.is_deleted
     *
     * @param isDeleted the value for project_contact_relation.is_deleted
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_contact_relation
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectId=").append(projectId);
        sb.append(", contactId=").append(contactId);
        sb.append(", insertBy=").append(insertBy);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remarks=").append(remarks);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}