package com.create80.rd.modules.projectmanager.api.model;

import java.io.Serializable;
import java.util.Date;

public class ProjectTemplate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.id
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.project_id
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.create_by
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.create_date
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.update_by
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.update_date
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.remarks
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.del_flag
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.template_name
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.template
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    private String template;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.apply_num
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    private Integer applyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_template
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.id
     *
     * @return the value of project_template.id
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.id
     *
     * @param id the value for project_template.id
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.project_id
     *
     * @return the value of project_template.project_id
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.project_id
     *
     * @param projectId the value for project_template.project_id
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.create_by
     *
     * @return the value of project_template.create_by
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.create_by
     *
     * @param createBy the value for project_template.create_by
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.create_date
     *
     * @return the value of project_template.create_date
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.create_date
     *
     * @param createDate the value for project_template.create_date
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.update_by
     *
     * @return the value of project_template.update_by
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.update_by
     *
     * @param updateBy the value for project_template.update_by
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.update_date
     *
     * @return the value of project_template.update_date
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.update_date
     *
     * @param updateDate the value for project_template.update_date
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.remarks
     *
     * @return the value of project_template.remarks
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.remarks
     *
     * @param remarks the value for project_template.remarks
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.del_flag
     *
     * @return the value of project_template.del_flag
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.del_flag
     *
     * @param delFlag the value for project_template.del_flag
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.template_name
     *
     * @return the value of project_template.template_name
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.template_name
     *
     * @param templateName the value for project_template.template_name
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.template
     *
     * @return the value of project_template.template
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.template
     *
     * @param template the value for project_template.template
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public void setTemplate(String template) {
        this.template = template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.apply_num
     *
     * @return the value of project_template.apply_num
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public Integer getApplyNum() {
        return applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.apply_num
     *
     * @param applyNum the value for project_template.apply_num
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    public void setApplyNum(Integer applyNum) {
        this.applyNum = applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_template
     *
     * @mbg.generated Thu May 31 17:04:34 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectId=").append(projectId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", remarks=").append(remarks);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", templateName=").append(templateName);
        sb.append(", template=").append(template);
        sb.append(", applyNum=").append(applyNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}