package com.create80.rd.modules.projectmanager.api.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Project implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_code
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String projectCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_description
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String projectDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_type
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String projectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_status
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String projectStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.manager_id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.plan_start_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private Date planStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.plan_end_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private Date planEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.actual_start_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private Date actualStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.actual_end_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private Date actualEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.progress
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String progress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.insert_by
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String insertBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.insert_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_by
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.remarks
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.is_deleted
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private String isDeleted;

    private List<ProjectContactRelation> projectContactRelationList;

    private List<ProjectMember> projectMemberList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_code
     *
     * @return the value of project.project_code
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_code
     *
     * @param projectCode the value for project.project_code
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_description
     *
     * @return the value of project.project_description
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getProjectDescription() {
        return projectDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_description
     *
     * @param projectDescription the value for project.project_description
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setProjectDescription(String projectDescription) {
        this.projectDescription = projectDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_type
     *
     * @return the value of project.project_type
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_type
     *
     * @param projectType the value for project.project_type
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setProjectType(String projectType) {
        this.projectType = projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_status
     *
     * @return the value of project.project_status
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getProjectStatus() {
        return projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_status
     *
     * @param projectStatus the value for project.project_status
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setProjectStatus(String projectStatus) {
        this.projectStatus = projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.manager_id
     *
     * @return the value of project.manager_id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.manager_id
     *
     * @param managerId the value for project.manager_id
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.plan_start_time
     *
     * @return the value of project.plan_start_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public Date getPlanStartTime() {
        return planStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.plan_start_time
     *
     * @param planStartTime the value for project.plan_start_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setPlanStartTime(Date planStartTime) {
        this.planStartTime = planStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.plan_end_time
     *
     * @return the value of project.plan_end_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public Date getPlanEndTime() {
        return planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.plan_end_time
     *
     * @param planEndTime the value for project.plan_end_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.actual_start_time
     *
     * @return the value of project.actual_start_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public Date getActualStartTime() {
        return actualStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.actual_start_time
     *
     * @param actualStartTime the value for project.actual_start_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setActualStartTime(Date actualStartTime) {
        this.actualStartTime = actualStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.actual_end_time
     *
     * @return the value of project.actual_end_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public Date getActualEndTime() {
        return actualEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.actual_end_time
     *
     * @param actualEndTime the value for project.actual_end_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setActualEndTime(Date actualEndTime) {
        this.actualEndTime = actualEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.progress
     *
     * @return the value of project.progress
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.progress
     *
     * @param progress the value for project.progress
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setProgress(String progress) {
        this.progress = progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.insert_by
     *
     * @return the value of project.insert_by
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getInsertBy() {
        return insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.insert_by
     *
     * @param insertBy the value for project.insert_by
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setInsertBy(String insertBy) {
        this.insertBy = insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.insert_time
     *
     * @return the value of project.insert_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.insert_time
     *
     * @param insertTime the value for project.insert_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_by
     *
     * @return the value of project.update_by
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_by
     *
     * @param updateBy the value for project.update_by
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_time
     *
     * @return the value of project.update_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_time
     *
     * @param updateTime the value for project.update_time
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.remarks
     *
     * @return the value of project.remarks
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.remarks
     *
     * @param remarks the value for project.remarks
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.is_deleted
     *
     * @return the value of project.is_deleted
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.is_deleted
     *
     * @param isDeleted the value for project.is_deleted
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    public List<ProjectContactRelation> getProjectContactRelationList() {
        return projectContactRelationList;
    }

    public void setProjectContactRelationList(List<ProjectContactRelation> projectContactRelationList) {
        this.projectContactRelationList=projectContactRelationList;
    }

    public List<ProjectMember> getProjectMemberList() {
        return projectMemberList;
    }

    public void setProjectMemberList(List<ProjectMember> projectMemberList) {
        this.projectMemberList=projectMemberList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jun 20 15:54:29 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectCode=").append(projectCode);
        sb.append(", projectName=").append(projectName);
        sb.append(", projectDescription=").append(projectDescription);
        sb.append(", projectType=").append(projectType);
        sb.append(", projectStatus=").append(projectStatus);
        sb.append(", managerId=").append(managerId);
        sb.append(", planStartTime=").append(planStartTime);
        sb.append(", planEndTime=").append(planEndTime);
        sb.append(", actualStartTime=").append(actualStartTime);
        sb.append(", actualEndTime=").append(actualEndTime);
        sb.append(", progress=").append(progress);
        sb.append(", insertBy=").append(insertBy);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remarks=").append(remarks);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", projectContactRelationList=").append(projectContactRelationList);
        sb.append(", projectMemberList=").append(projectMemberList);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}