package com.create80.rd.modules.projectmanager.api.model;

import java.io.Serializable;
import java.util.Date;

public class ProjectTemplate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.id
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.project_id
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.insert_by
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    private String insertBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.insert_time
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.update_by
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.update_time
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.remarks
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.is_deleted
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    private String isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.template_name
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.template
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    private String template;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_template.apply_num
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    private Integer applyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_template
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.id
     *
     * @return the value of project_template.id
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.id
     *
     * @param id the value for project_template.id
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.project_id
     *
     * @return the value of project_template.project_id
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.project_id
     *
     * @param projectId the value for project_template.project_id
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.insert_by
     *
     * @return the value of project_template.insert_by
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public String getInsertBy() {
        return insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.insert_by
     *
     * @param insertBy the value for project_template.insert_by
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public void setInsertBy(String insertBy) {
        this.insertBy = insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.insert_time
     *
     * @return the value of project_template.insert_time
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.insert_time
     *
     * @param insertTime the value for project_template.insert_time
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.update_by
     *
     * @return the value of project_template.update_by
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.update_by
     *
     * @param updateBy the value for project_template.update_by
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.update_time
     *
     * @return the value of project_template.update_time
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.update_time
     *
     * @param updateTime the value for project_template.update_time
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.remarks
     *
     * @return the value of project_template.remarks
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.remarks
     *
     * @param remarks the value for project_template.remarks
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.is_deleted
     *
     * @return the value of project_template.is_deleted
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.is_deleted
     *
     * @param isDeleted the value for project_template.is_deleted
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.template_name
     *
     * @return the value of project_template.template_name
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.template_name
     *
     * @param templateName the value for project_template.template_name
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.template
     *
     * @return the value of project_template.template
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.template
     *
     * @param template the value for project_template.template
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public void setTemplate(String template) {
        this.template = template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_template.apply_num
     *
     * @return the value of project_template.apply_num
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public Integer getApplyNum() {
        return applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_template.apply_num
     *
     * @param applyNum the value for project_template.apply_num
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    public void setApplyNum(Integer applyNum) {
        this.applyNum = applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_template
     *
     * @mbg.generated Wed Jun 20 15:54:47 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectId=").append(projectId);
        sb.append(", insertBy=").append(insertBy);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remarks=").append(remarks);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", templateName=").append(templateName);
        sb.append(", template=").append(template);
        sb.append(", applyNum=").append(applyNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}