package com.create80.rd.modules.assets.api.model;

import java.io.Serializable;
import java.util.Date;

public class AssetsReplace implements Serializable {

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.id
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.replace_no
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private String replaceNo;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.original_assets_id
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private String originalAssetsId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.replace_assets_id
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private String replaceAssetsId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.replace_manager_id
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private String replaceManagerId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.replace_time
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private Date replaceTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.replace_reason
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private String replaceReason;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.create_by
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private String createBy;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.create_date
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private Date createDate;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.update_by
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private String updateBy;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.update_date
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private Date updateDate;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.remarks
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private String remarks;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_replace.del_flag
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private String delFlag;

  private AssetsManager originalAssetsManager;
  private AssetsManager replaceAssetsManager;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table assets_replace
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.id
   *
   * @return the value of assets_replace.id
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.id
   *
   * @param id the value for assets_replace.id
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.replace_no
   *
   * @return the value of assets_replace.replace_no
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public String getReplaceNo() {
    return replaceNo;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.replace_no
   *
   * @param replaceNo the value for assets_replace.replace_no
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setReplaceNo(String replaceNo) {
    this.replaceNo = replaceNo;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.original_assets_id
   *
   * @return the value of assets_replace.original_assets_id
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public String getOriginalAssetsId() {
    return originalAssetsId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.original_assets_id
   *
   * @param originalAssetsId the value for assets_replace.original_assets_id
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setOriginalAssetsId(String originalAssetsId) {
    this.originalAssetsId = originalAssetsId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.replace_assets_id
   *
   * @return the value of assets_replace.replace_assets_id
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public String getReplaceAssetsId() {
    return replaceAssetsId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.replace_assets_id
   *
   * @param replaceAssetsId the value for assets_replace.replace_assets_id
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setReplaceAssetsId(String replaceAssetsId) {
    this.replaceAssetsId = replaceAssetsId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.replace_manager_id
   *
   * @return the value of assets_replace.replace_manager_id
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public String getReplaceManagerId() {
    return replaceManagerId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.replace_manager_id
   *
   * @param replaceManagerId the value for assets_replace.replace_manager_id
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setReplaceManagerId(String replaceManagerId) {
    this.replaceManagerId = replaceManagerId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.replace_time
   *
   * @return the value of assets_replace.replace_time
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public Date getReplaceTime() {
    return replaceTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.replace_time
   *
   * @param replaceTime the value for assets_replace.replace_time
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setReplaceTime(Date replaceTime) {
    this.replaceTime = replaceTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.replace_reason
   *
   * @return the value of assets_replace.replace_reason
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public String getReplaceReason() {
    return replaceReason;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.replace_reason
   *
   * @param replaceReason the value for assets_replace.replace_reason
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setReplaceReason(String replaceReason) {
    this.replaceReason = replaceReason;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.create_by
   *
   * @return the value of assets_replace.create_by
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public String getCreateBy() {
    return createBy;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.create_by
   *
   * @param createBy the value for assets_replace.create_by
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.create_date
   *
   * @return the value of assets_replace.create_date
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public Date getCreateDate() {
    return createDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.create_date
   *
   * @param createDate the value for assets_replace.create_date
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.update_by
   *
   * @return the value of assets_replace.update_by
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public String getUpdateBy() {
    return updateBy;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.update_by
   *
   * @param updateBy the value for assets_replace.update_by
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.update_date
   *
   * @return the value of assets_replace.update_date
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public Date getUpdateDate() {
    return updateDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.update_date
   *
   * @param updateDate the value for assets_replace.update_date
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.remarks
   *
   * @return the value of assets_replace.remarks
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public String getRemarks() {
    return remarks;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.remarks
   *
   * @param remarks the value for assets_replace.remarks
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_replace.del_flag
   *
   * @return the value of assets_replace.del_flag
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public String getDelFlag() {
    return delFlag;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_replace.del_flag
   *
   * @param delFlag the value for assets_replace.del_flag
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  public void setDelFlag(String delFlag) {
    this.delFlag = delFlag;
  }

  public AssetsManager getOriginalAssetsManager() {
    return originalAssetsManager;
  }

  public void setOriginalAssetsManager(
      AssetsManager originalAssetsManager) {
    this.originalAssetsManager = originalAssetsManager;
  }

  public AssetsManager getReplaceAssetsManager() {
    return replaceAssetsManager;
  }

  public void setReplaceAssetsManager(
      AssetsManager replaceAssetsManager) {
    this.replaceAssetsManager = replaceAssetsManager;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table assets_replace
   *
   * @mbg.generated Thu Jun 07 12:42:37 CST 2018
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" [");
    sb.append("Hash = ").append(hashCode());
    sb.append(", id=").append(id);
    sb.append(", replaceNo=").append(replaceNo);
    sb.append(", originalAssetsId=").append(originalAssetsId);
    sb.append(", replaceAssetsId=").append(replaceAssetsId);
    sb.append(", replaceManagerId=").append(replaceManagerId);
    sb.append(", replaceTime=").append(replaceTime);
    sb.append(", replaceReason=").append(replaceReason);
    sb.append(", createBy=").append(createBy);
    sb.append(", createDate=").append(createDate);
    sb.append(", updateBy=").append(updateBy);
    sb.append(", updateDate=").append(updateDate);
    sb.append(", remarks=").append(remarks);
    sb.append(", delFlag=").append(delFlag);
    sb.append(", serialVersionUID=").append(serialVersionUID);
    sb.append("]");
    return sb.toString();
  }
}