package com.create80.rd.modules.assets.api.model;

import java.io.Serializable;
import java.util.Date;

public class AssetsCarDistributive implements Serializable {

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_distributive.id
   *
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_distributive.assets_id
   *
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  private String assetsId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_distributive.group_id
   *
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  private String groupId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_distributive.insert_by
   *
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  private String insertBy;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_distributive.insert_time
   *
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  private Date insertTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_distributive.update_by
   *
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  private String updateBy;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_distributive.update_time
   *
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  private Date updateTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_distributive.remarks
   *
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  private String remarks;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_distributive.is_deleted
   *
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  private String isDeleted;


  private AssetsManager assetsManager;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table assets_car_distributive
   *
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_distributive.id
   *
   * @return the value of assets_car_distributive.id
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_distributive.id
   *
   * @param id the value for assets_car_distributive.id
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_distributive.assets_id
   *
   * @return the value of assets_car_distributive.assets_id
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public String getAssetsId() {
    return assetsId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_distributive.assets_id
   *
   * @param assetsId the value for assets_car_distributive.assets_id
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public void setAssetsId(String assetsId) {
    this.assetsId = assetsId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_distributive.group_id
   *
   * @return the value of assets_car_distributive.group_id
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public String getGroupId() {
    return groupId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_distributive.group_id
   *
   * @param groupId the value for assets_car_distributive.group_id
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_distributive.insert_by
   *
   * @return the value of assets_car_distributive.insert_by
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public String getInsertBy() {
    return insertBy;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_distributive.insert_by
   *
   * @param insertBy the value for assets_car_distributive.insert_by
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public void setInsertBy(String insertBy) {
    this.insertBy = insertBy;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_distributive.insert_time
   *
   * @return the value of assets_car_distributive.insert_time
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public Date getInsertTime() {
    return insertTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_distributive.insert_time
   *
   * @param insertTime the value for assets_car_distributive.insert_time
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public void setInsertTime(Date insertTime) {
    this.insertTime = insertTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_distributive.update_by
   *
   * @return the value of assets_car_distributive.update_by
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public String getUpdateBy() {
    return updateBy;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_distributive.update_by
   *
   * @param updateBy the value for assets_car_distributive.update_by
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_distributive.update_time
   *
   * @return the value of assets_car_distributive.update_time
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_distributive.update_time
   *
   * @param updateTime the value for assets_car_distributive.update_time
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_distributive.remarks
   *
   * @return the value of assets_car_distributive.remarks
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public String getRemarks() {
    return remarks;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_distributive.remarks
   *
   * @param remarks the value for assets_car_distributive.remarks
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_distributive.is_deleted
   *
   * @return the value of assets_car_distributive.is_deleted
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public String getIsDeleted() {
    return isDeleted;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_distributive.is_deleted
   *
   * @param isDeleted the value for assets_car_distributive.is_deleted
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  public void setIsDeleted(String isDeleted) {
    this.isDeleted = isDeleted;
  }


  public AssetsManager getAssetsManager() {
    return assetsManager;
  }

  public void setAssetsManager(AssetsManager assetsManager) {
    this.assetsManager = assetsManager;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table assets_car_distributive
   *
   * @mbg.generated Wed Jun 20 16:41:16 CST 2018
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" [");
    sb.append("Hash = ").append(hashCode());
    sb.append(", id=").append(id);
    sb.append(", assetsId=").append(assetsId);
    sb.append(", groupId=").append(groupId);
    sb.append(", insertBy=").append(insertBy);
    sb.append(", insertTime=").append(insertTime);
    sb.append(", updateBy=").append(updateBy);
    sb.append(", updateTime=").append(updateTime);
    sb.append(", remarks=").append(remarks);
    sb.append(", isDeleted=").append(isDeleted);
    sb.append(", serialVersionUID=").append(serialVersionUID);
    sb.append("]");
    return sb.toString();
  }
}