package com.create80.rd.modules.assets.api.model;

import java.io.Serializable;
import java.util.Date;

public class AssetsCarUse implements Serializable {

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.id
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.assets_id
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private String assetsId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.manager_id
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private String managerId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.use_purpose
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private String usePurpose;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.before_mileage
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private String beforeMileage;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.after_mileage
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private String afterMileage;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.start_time
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private Date startTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.end_time
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private Date endTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.create_by
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private String createBy;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.create_date
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private Date createDate;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.update_by
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private String updateBy;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.update_date
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private Date updateDate;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.remarks
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private String remarks;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column assets_car_use.del_flag
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private String delFlag;


  private AssetsManager assetsManager;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table assets_car_use
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.id
   *
   * @return the value of assets_car_use.id
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.id
   *
   * @param id the value for assets_car_use.id
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.assets_id
   *
   * @return the value of assets_car_use.assets_id
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public String getAssetsId() {
    return assetsId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.assets_id
   *
   * @param assetsId the value for assets_car_use.assets_id
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setAssetsId(String assetsId) {
    this.assetsId = assetsId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.manager_id
   *
   * @return the value of assets_car_use.manager_id
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public String getManagerId() {
    return managerId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.manager_id
   *
   * @param managerId the value for assets_car_use.manager_id
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setManagerId(String managerId) {
    this.managerId = managerId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.use_purpose
   *
   * @return the value of assets_car_use.use_purpose
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public String getUsePurpose() {
    return usePurpose;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.use_purpose
   *
   * @param usePurpose the value for assets_car_use.use_purpose
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setUsePurpose(String usePurpose) {
    this.usePurpose = usePurpose;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.before_mileage
   *
   * @return the value of assets_car_use.before_mileage
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public String getBeforeMileage() {
    return beforeMileage;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.before_mileage
   *
   * @param beforeMileage the value for assets_car_use.before_mileage
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setBeforeMileage(String beforeMileage) {
    this.beforeMileage = beforeMileage;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.after_mileage
   *
   * @return the value of assets_car_use.after_mileage
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public String getAfterMileage() {
    return afterMileage;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.after_mileage
   *
   * @param afterMileage the value for assets_car_use.after_mileage
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setAfterMileage(String afterMileage) {
    this.afterMileage = afterMileage;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.start_time
   *
   * @return the value of assets_car_use.start_time
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public Date getStartTime() {
    return startTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.start_time
   *
   * @param startTime the value for assets_car_use.start_time
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setStartTime(Date startTime) {
    this.startTime = startTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.end_time
   *
   * @return the value of assets_car_use.end_time
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public Date getEndTime() {
    return endTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.end_time
   *
   * @param endTime the value for assets_car_use.end_time
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setEndTime(Date endTime) {
    this.endTime = endTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.create_by
   *
   * @return the value of assets_car_use.create_by
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public String getCreateBy() {
    return createBy;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.create_by
   *
   * @param createBy the value for assets_car_use.create_by
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.create_date
   *
   * @return the value of assets_car_use.create_date
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public Date getCreateDate() {
    return createDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.create_date
   *
   * @param createDate the value for assets_car_use.create_date
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.update_by
   *
   * @return the value of assets_car_use.update_by
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public String getUpdateBy() {
    return updateBy;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.update_by
   *
   * @param updateBy the value for assets_car_use.update_by
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.update_date
   *
   * @return the value of assets_car_use.update_date
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public Date getUpdateDate() {
    return updateDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.update_date
   *
   * @param updateDate the value for assets_car_use.update_date
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.remarks
   *
   * @return the value of assets_car_use.remarks
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public String getRemarks() {
    return remarks;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.remarks
   *
   * @param remarks the value for assets_car_use.remarks
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column assets_car_use.del_flag
   *
   * @return the value of assets_car_use.del_flag
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public String getDelFlag() {
    return delFlag;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column assets_car_use.del_flag
   *
   * @param delFlag the value for assets_car_use.del_flag
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  public void setDelFlag(String delFlag) {
    this.delFlag = delFlag;
  }


  public AssetsManager getAssetsManager() {
    return assetsManager;
  }

  public void setAssetsManager(AssetsManager assetsManager) {
    this.assetsManager = assetsManager;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table assets_car_use
   *
   * @mbg.generated Fri Jun 08 17:12:51 CST 2018
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" [");
    sb.append("Hash = ").append(hashCode());
    sb.append(", id=").append(id);
    sb.append(", assetsId=").append(assetsId);
    sb.append(", managerId=").append(managerId);
    sb.append(", usePurpose=").append(usePurpose);
    sb.append(", beforeMileage=").append(beforeMileage);
    sb.append(", afterMileage=").append(afterMileage);
    sb.append(", startTime=").append(startTime);
    sb.append(", endTime=").append(endTime);
    sb.append(", createBy=").append(createBy);
    sb.append(", createDate=").append(createDate);
    sb.append(", updateBy=").append(updateBy);
    sb.append(", updateDate=").append(updateDate);
    sb.append(", remarks=").append(remarks);
    sb.append(", delFlag=").append(delFlag);
    sb.append(", serialVersionUID=").append(serialVersionUID);
    sb.append("]");
    return sb.toString();
  }
}