package com.create80.rd.modules.assets.api.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class AssetsManager implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.id
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.assets_no
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String assetsNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.assets_type
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String assetsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.assets_name
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String assetsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.original_manufactor
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String originalManufactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.assets_model
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String assetsModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.assets_serial_num
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String assetsSerialNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.assets_nature
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String assetsNature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.assets_use_department
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String assetsUseDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.assets_use_unit
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String assetsUseUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.assets_location
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String assetsLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.repair_start_time
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private Date repairStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.repair_end_time
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private Date repairEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.assets_status
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String assetsStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.plate_number
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String plateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.manager_id
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.create_by
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.create_date
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.update_by
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.update_date
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.remarks
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.del_flag
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assets_manager.contact_id
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private String contactId;

    private List<AssetsImage> assetsImageList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table assets_manager
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.id
     *
     * @return the value of assets_manager.id
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.id
     *
     * @param id the value for assets_manager.id
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.assets_no
     *
     * @return the value of assets_manager.assets_no
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getAssetsNo() {
        return assetsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.assets_no
     *
     * @param assetsNo the value for assets_manager.assets_no
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setAssetsNo(String assetsNo) {
        this.assetsNo = assetsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.assets_type
     *
     * @return the value of assets_manager.assets_type
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getAssetsType() {
        return assetsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.assets_type
     *
     * @param assetsType the value for assets_manager.assets_type
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setAssetsType(String assetsType) {
        this.assetsType = assetsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.assets_name
     *
     * @return the value of assets_manager.assets_name
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getAssetsName() {
        return assetsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.assets_name
     *
     * @param assetsName the value for assets_manager.assets_name
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setAssetsName(String assetsName) {
        this.assetsName = assetsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.original_manufactor
     *
     * @return the value of assets_manager.original_manufactor
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getOriginalManufactor() {
        return originalManufactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.original_manufactor
     *
     * @param originalManufactor the value for assets_manager.original_manufactor
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setOriginalManufactor(String originalManufactor) {
        this.originalManufactor = originalManufactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.assets_model
     *
     * @return the value of assets_manager.assets_model
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getAssetsModel() {
        return assetsModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.assets_model
     *
     * @param assetsModel the value for assets_manager.assets_model
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setAssetsModel(String assetsModel) {
        this.assetsModel = assetsModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.assets_serial_num
     *
     * @return the value of assets_manager.assets_serial_num
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getAssetsSerialNum() {
        return assetsSerialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.assets_serial_num
     *
     * @param assetsSerialNum the value for assets_manager.assets_serial_num
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setAssetsSerialNum(String assetsSerialNum) {
        this.assetsSerialNum = assetsSerialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.assets_nature
     *
     * @return the value of assets_manager.assets_nature
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getAssetsNature() {
        return assetsNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.assets_nature
     *
     * @param assetsNature the value for assets_manager.assets_nature
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setAssetsNature(String assetsNature) {
        this.assetsNature = assetsNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.assets_use_department
     *
     * @return the value of assets_manager.assets_use_department
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getAssetsUseDepartment() {
        return assetsUseDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.assets_use_department
     *
     * @param assetsUseDepartment the value for assets_manager.assets_use_department
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setAssetsUseDepartment(String assetsUseDepartment) {
        this.assetsUseDepartment = assetsUseDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.assets_use_unit
     *
     * @return the value of assets_manager.assets_use_unit
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getAssetsUseUnit() {
        return assetsUseUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.assets_use_unit
     *
     * @param assetsUseUnit the value for assets_manager.assets_use_unit
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setAssetsUseUnit(String assetsUseUnit) {
        this.assetsUseUnit = assetsUseUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.assets_location
     *
     * @return the value of assets_manager.assets_location
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getAssetsLocation() {
        return assetsLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.assets_location
     *
     * @param assetsLocation the value for assets_manager.assets_location
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setAssetsLocation(String assetsLocation) {
        this.assetsLocation = assetsLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.repair_start_time
     *
     * @return the value of assets_manager.repair_start_time
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public Date getRepairStartTime() {
        return repairStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.repair_start_time
     *
     * @param repairStartTime the value for assets_manager.repair_start_time
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setRepairStartTime(Date repairStartTime) {
        this.repairStartTime = repairStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.repair_end_time
     *
     * @return the value of assets_manager.repair_end_time
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public Date getRepairEndTime() {
        return repairEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.repair_end_time
     *
     * @param repairEndTime the value for assets_manager.repair_end_time
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setRepairEndTime(Date repairEndTime) {
        this.repairEndTime = repairEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.assets_status
     *
     * @return the value of assets_manager.assets_status
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getAssetsStatus() {
        return assetsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.assets_status
     *
     * @param assetsStatus the value for assets_manager.assets_status
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setAssetsStatus(String assetsStatus) {
        this.assetsStatus = assetsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.plate_number
     *
     * @return the value of assets_manager.plate_number
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.plate_number
     *
     * @param plateNumber the value for assets_manager.plate_number
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.manager_id
     *
     * @return the value of assets_manager.manager_id
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.manager_id
     *
     * @param managerId the value for assets_manager.manager_id
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.create_by
     *
     * @return the value of assets_manager.create_by
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.create_by
     *
     * @param createBy the value for assets_manager.create_by
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.create_date
     *
     * @return the value of assets_manager.create_date
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.create_date
     *
     * @param createDate the value for assets_manager.create_date
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.update_by
     *
     * @return the value of assets_manager.update_by
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.update_by
     *
     * @param updateBy the value for assets_manager.update_by
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.update_date
     *
     * @return the value of assets_manager.update_date
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.update_date
     *
     * @param updateDate the value for assets_manager.update_date
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.remarks
     *
     * @return the value of assets_manager.remarks
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.remarks
     *
     * @param remarks the value for assets_manager.remarks
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.del_flag
     *
     * @return the value of assets_manager.del_flag
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.del_flag
     *
     * @param delFlag the value for assets_manager.del_flag
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assets_manager.contact_id
     *
     * @return the value of assets_manager.contact_id
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public String getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assets_manager.contact_id
     *
     * @param contactId the value for assets_manager.contact_id
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    public void setContactId(String contactId) {
        this.contactId = contactId;
    }

    public List<AssetsImage> getAssetsImageList() {
        return assetsImageList;
    }

    public void setAssetsImageList(List<AssetsImage> assetsImageList) {
        this.assetsImageList=assetsImageList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assets_manager
     *
     * @mbg.generated Tue Jun 05 18:11:43 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", assetsNo=").append(assetsNo);
        sb.append(", assetsType=").append(assetsType);
        sb.append(", assetsName=").append(assetsName);
        sb.append(", originalManufactor=").append(originalManufactor);
        sb.append(", assetsModel=").append(assetsModel);
        sb.append(", assetsSerialNum=").append(assetsSerialNum);
        sb.append(", assetsNature=").append(assetsNature);
        sb.append(", assetsUseDepartment=").append(assetsUseDepartment);
        sb.append(", assetsUseUnit=").append(assetsUseUnit);
        sb.append(", assetsLocation=").append(assetsLocation);
        sb.append(", repairStartTime=").append(repairStartTime);
        sb.append(", repairEndTime=").append(repairEndTime);
        sb.append(", assetsStatus=").append(assetsStatus);
        sb.append(", plateNumber=").append(plateNumber);
        sb.append(", managerId=").append(managerId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", remarks=").append(remarks);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", contactId=").append(contactId);
        sb.append(", assetsImageList=").append(assetsImageList);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}