package com.create80.rd.modules.customer.eiareport.api.model;

import com.create80.rd.modules.customer.enterprise.api.model.Enterprise;
import com.create80.rd.modules.customer.pt.api.model.PollutionType;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class EiaReport implements Serializable {

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report.id
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report.enterprise_id
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  private String enterpriseId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report.approved
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  private String approved;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report.approve_date
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  private Date approveDate;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report.accepted
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  private String accepted;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report.accept_date
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  private Date acceptDate;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report.expanded
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  private String expanded;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report.expended_device
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  private String expendedDevice;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report.pollution_type_id
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  private String pollutionTypeId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report.pollution_permit_status
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  private String pollutionPermitStatus;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report.report_file
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  private String reportFile;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report_pic.insert_by
   *
   * @mbg.generated Wed Jun 20 14:06:43 CST 2018
   */
  private String insertBy;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report_pic.insert_time
   *
   * @mbg.generated Wed Jun 20 14:06:43 CST 2018
   */
  private Date insertTime;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report_pic.update_by
   *
   * @mbg.generated Wed Jun 20 14:06:43 CST 2018
   */
  private String updateBy;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report_pic.update_time
   *
   * @mbg.generated Wed Jun 20 14:06:43 CST 2018
   */
  private Date updateTime;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report_pic.remarks
   *
   * @mbg.generated Wed Jun 20 14:06:43 CST 2018
   */
  private String remarks;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column eia_report_pic.is_deleted
   *
   * @mbg.generated Wed Jun 20 14:06:43 CST 2018
   */
  private String isDeleted;

  private Enterprise enterprise;
  private PollutionType pollutionType;

  private List<EiaReportPic> eiaReportPicList;

  private List<EiaReportWaste> eiaReportWasteList;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table eia_report
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column eia_report.id
   *
   * @return the value of eia_report.id
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column eia_report.id
   *
   * @param id the value for eia_report.id
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column eia_report.enterprise_id
   *
   * @return the value of eia_report.enterprise_id
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public String getEnterpriseId() {
    return enterpriseId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column eia_report.enterprise_id
   *
   * @param enterpriseId the value for eia_report.enterprise_id
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public void setEnterpriseId(String enterpriseId) {
    this.enterpriseId = enterpriseId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column eia_report.approved
   *
   * @return the value of eia_report.approved
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public String getApproved() {
    return approved;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column eia_report.approved
   *
   * @param approved the value for eia_report.approved
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public void setApproved(String approved) {
    this.approved = approved;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column eia_report.approve_date
   *
   * @return the value of eia_report.approve_date
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public Date getApproveDate() {
    return approveDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column eia_report.approve_date
   *
   * @param approveDate the value for eia_report.approve_date
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public void setApproveDate(Date approveDate) {
    this.approveDate = approveDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column eia_report.accepted
   *
   * @return the value of eia_report.accepted
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public String getAccepted() {
    return accepted;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column eia_report.accepted
   *
   * @param accepted the value for eia_report.accepted
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public void setAccepted(String accepted) {
    this.accepted = accepted;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column eia_report.accept_date
   *
   * @return the value of eia_report.accept_date
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public Date getAcceptDate() {
    return acceptDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column eia_report.accept_date
   *
   * @param acceptDate the value for eia_report.accept_date
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public void setAcceptDate(Date acceptDate) {
    this.acceptDate = acceptDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column eia_report.expanded
   *
   * @return the value of eia_report.expanded
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public String getExpanded() {
    return expanded;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column eia_report.expanded
   *
   * @param expanded the value for eia_report.expanded
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public void setExpanded(String expanded) {
    this.expanded = expanded;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column eia_report.expended_device
   *
   * @return the value of eia_report.expended_device
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public String getExpendedDevice() {
    return expendedDevice;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column eia_report.expended_device
   *
   * @param expendedDevice the value for eia_report.expended_device
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public void setExpendedDevice(String expendedDevice) {
    this.expendedDevice = expendedDevice;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column eia_report.pollution_type_id
   *
   * @return the value of eia_report.pollution_type_id
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public String getPollutionTypeId() {
    return pollutionTypeId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column eia_report.pollution_type_id
   *
   * @param pollutionTypeId the value for eia_report.pollution_type_id
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public void setPollutionTypeId(String pollutionTypeId) {
    this.pollutionTypeId = pollutionTypeId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column eia_report.pollution_permit_status
   *
   * @return the value of eia_report.pollution_permit_status
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public String getPollutionPermitStatus() {
    return pollutionPermitStatus;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column eia_report.pollution_permit_status
   *
   * @param pollutionPermitStatus the value for eia_report.pollution_permit_status
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public void setPollutionPermitStatus(String pollutionPermitStatus) {
    this.pollutionPermitStatus = pollutionPermitStatus;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column eia_report.report_file
   *
   * @return the value of eia_report.report_file
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public String getReportFile() {
    return reportFile;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column eia_report.report_file
   *
   * @param reportFile the value for eia_report.report_file
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  public void setReportFile(String reportFile) {
    this.reportFile = reportFile;
  }

  public String getInsertBy() {
    return insertBy;
  }

  public void setInsertBy(String insertBy) {
    this.insertBy = insertBy;
  }

  public Date getInsertTime() {
    return insertTime;
  }

  public void setInsertTime(Date insertTime) {
    this.insertTime = insertTime;
  }

  public String getUpdateBy() {
    return updateBy;
  }

  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  public Date getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  public String getRemarks() {
    return remarks;
  }

  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }

  public String getIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(String isDeleted) {
    this.isDeleted = isDeleted;
  }

  public List<EiaReportPic> getEiaReportPicList() {
    return eiaReportPicList;
  }

  public void setEiaReportPicList(List<EiaReportPic> eiaReportPicList) {
    this.eiaReportPicList = eiaReportPicList;
  }

  public List<EiaReportWaste> getEiaReportWasteList() {
    return eiaReportWasteList;
  }

  public void setEiaReportWasteList(List<EiaReportWaste> eiaReportWasteList) {
    this.eiaReportWasteList = eiaReportWasteList;
  }

  public Enterprise getEnterprise() {
    return enterprise;
  }

  public void setEnterprise(Enterprise enterprise) {
    this.enterprise = enterprise;
  }

  public PollutionType getPollutionType() {
    return pollutionType;
  }

  public void setPollutionType(PollutionType pollutionType) {
    this.pollutionType = pollutionType;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table eia_report
   *
   * @mbg.generated Thu May 24 19:14:48 CST 2018
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" [");
    sb.append("Hash = ").append(hashCode());
    sb.append(", id=").append(id);
    sb.append(", enterpriseId=").append(enterpriseId);
    sb.append(", approved=").append(approved);
    sb.append(", approveDate=").append(approveDate);
    sb.append(", accepted=").append(accepted);
    sb.append(", acceptDate=").append(acceptDate);
    sb.append(", expanded=").append(expanded);
    sb.append(", expendedDevice=").append(expendedDevice);
    sb.append(", pollutionTypeId=").append(pollutionTypeId);
    sb.append(", pollutionPermitStatus=").append(pollutionPermitStatus);
    sb.append(", reportFile=").append(reportFile);
    sb.append(", insertBy=").append(insertBy);
    sb.append(", insertTime=").append(insertTime);
    sb.append(", updateBy=").append(updateBy);
    sb.append(", updateTime=").append(updateTime);
    sb.append(", remarks=").append(remarks);
    sb.append(", isDeleted=").append(isDeleted);
    sb.append(", eiaReportPicList=").append(eiaReportPicList);
    sb.append(", eiaReportWasteList=").append(eiaReportWasteList);
    sb.append(", serialVersionUID=").append(serialVersionUID);
    sb.append("]");
    return sb.toString();
  }
}