package com.create80.rd.modules.customer.eiareport.api.model;

import com.create80.rd.modules.customer.enterprise.api.model.Enterprise;
import com.create80.rd.modules.customer.pt.api.model.PollutionType;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class EiaReport implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.id
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.enterprise_id
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.approved
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String approved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.approve_date
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private Date approveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.accepted
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String accepted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.accept_date
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private Date acceptDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.expanded
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String expanded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.expended_device
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String expendedDevice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.pollution_type_id
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String pollutionTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.pollution_permit_status
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String pollutionPermitStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.report_file
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String reportFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.create_by
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.create_date
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.update_by
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.update_date
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.remarks
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eia_report.del_flag
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private String delFlag;

    private Enterprise enterprise;
    private PollutionType pollutionType;

    private List<EiaReportPic> eiaReportPicList;

    private List<EiaReportWaste> eiaReportWasteList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eia_report
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.id
     *
     * @return the value of eia_report.id
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.id
     *
     * @param id the value for eia_report.id
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.enterprise_id
     *
     * @return the value of eia_report.enterprise_id
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.enterprise_id
     *
     * @param enterpriseId the value for eia_report.enterprise_id
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.approved
     *
     * @return the value of eia_report.approved
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getApproved() {
        return approved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.approved
     *
     * @param approved the value for eia_report.approved
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setApproved(String approved) {
        this.approved = approved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.approve_date
     *
     * @return the value of eia_report.approve_date
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public Date getApproveDate() {
        return approveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.approve_date
     *
     * @param approveDate the value for eia_report.approve_date
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setApproveDate(Date approveDate) {
        this.approveDate = approveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.accepted
     *
     * @return the value of eia_report.accepted
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getAccepted() {
        return accepted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.accepted
     *
     * @param accepted the value for eia_report.accepted
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setAccepted(String accepted) {
        this.accepted = accepted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.accept_date
     *
     * @return the value of eia_report.accept_date
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public Date getAcceptDate() {
        return acceptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.accept_date
     *
     * @param acceptDate the value for eia_report.accept_date
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setAcceptDate(Date acceptDate) {
        this.acceptDate = acceptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.expanded
     *
     * @return the value of eia_report.expanded
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getExpanded() {
        return expanded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.expanded
     *
     * @param expanded the value for eia_report.expanded
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setExpanded(String expanded) {
        this.expanded = expanded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.expended_device
     *
     * @return the value of eia_report.expended_device
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getExpendedDevice() {
        return expendedDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.expended_device
     *
     * @param expendedDevice the value for eia_report.expended_device
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setExpendedDevice(String expendedDevice) {
        this.expendedDevice = expendedDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.pollution_type_id
     *
     * @return the value of eia_report.pollution_type_id
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getPollutionTypeId() {
        return pollutionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.pollution_type_id
     *
     * @param pollutionTypeId the value for eia_report.pollution_type_id
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setPollutionTypeId(String pollutionTypeId) {
        this.pollutionTypeId = pollutionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.pollution_permit_status
     *
     * @return the value of eia_report.pollution_permit_status
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getPollutionPermitStatus() {
        return pollutionPermitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.pollution_permit_status
     *
     * @param pollutionPermitStatus the value for eia_report.pollution_permit_status
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setPollutionPermitStatus(String pollutionPermitStatus) {
        this.pollutionPermitStatus = pollutionPermitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.report_file
     *
     * @return the value of eia_report.report_file
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getReportFile() {
        return reportFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.report_file
     *
     * @param reportFile the value for eia_report.report_file
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setReportFile(String reportFile) {
        this.reportFile = reportFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.create_by
     *
     * @return the value of eia_report.create_by
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.create_by
     *
     * @param createBy the value for eia_report.create_by
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.create_date
     *
     * @return the value of eia_report.create_date
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.create_date
     *
     * @param createDate the value for eia_report.create_date
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.update_by
     *
     * @return the value of eia_report.update_by
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.update_by
     *
     * @param updateBy the value for eia_report.update_by
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.update_date
     *
     * @return the value of eia_report.update_date
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.update_date
     *
     * @param updateDate the value for eia_report.update_date
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.remarks
     *
     * @return the value of eia_report.remarks
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.remarks
     *
     * @param remarks the value for eia_report.remarks
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eia_report.del_flag
     *
     * @return the value of eia_report.del_flag
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eia_report.del_flag
     *
     * @param delFlag the value for eia_report.del_flag
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    public List<EiaReportPic> getEiaReportPicList() {
        return eiaReportPicList;
    }

    public void setEiaReportPicList(List<EiaReportPic> eiaReportPicList) {
        this.eiaReportPicList=eiaReportPicList;
    }

    public List<EiaReportWaste> getEiaReportWasteList() {
        return eiaReportWasteList;
    }

    public void setEiaReportWasteList(List<EiaReportWaste> eiaReportWasteList) {
        this.eiaReportWasteList=eiaReportWasteList;
    }

    public Enterprise getEnterprise() {
        return enterprise;
    }

    public void setEnterprise(Enterprise enterprise) {
        this.enterprise = enterprise;
    }

    public PollutionType getPollutionType() {
        return pollutionType;
    }

    public void setPollutionType(PollutionType pollutionType) {
        this.pollutionType = pollutionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eia_report
     *
     * @mbg.generated Thu May 24 19:14:48 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", enterpriseId=").append(enterpriseId);
        sb.append(", approved=").append(approved);
        sb.append(", approveDate=").append(approveDate);
        sb.append(", accepted=").append(accepted);
        sb.append(", acceptDate=").append(acceptDate);
        sb.append(", expanded=").append(expanded);
        sb.append(", expendedDevice=").append(expendedDevice);
        sb.append(", pollutionTypeId=").append(pollutionTypeId);
        sb.append(", pollutionPermitStatus=").append(pollutionPermitStatus);
        sb.append(", reportFile=").append(reportFile);
        sb.append(", createBy=").append(createBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", remarks=").append(remarks);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", eiaReportPicList=").append(eiaReportPicList);
        sb.append(", eiaReportWasteList=").append(eiaReportWasteList);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}