package com.knt.rd.modules.customer.it.api.model;

import java.io.Serializable;
import java.util.Date;

public class IndustryType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry_type.id
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry_type.industry_type_name
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    private String industryTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry_type.create_by
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry_type.create_date
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry_type.update_by
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry_type.update_date
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry_type.remarks
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column industry_type.del_flag
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table industry_type
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.id
     *
     * @return the value of industry_type.id
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.id
     *
     * @param id the value for industry_type.id
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.industry_type_name
     *
     * @return the value of industry_type.industry_type_name
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public String getIndustryTypeName() {
        return industryTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.industry_type_name
     *
     * @param industryTypeName the value for industry_type.industry_type_name
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public void setIndustryTypeName(String industryTypeName) {
        this.industryTypeName = industryTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.create_by
     *
     * @return the value of industry_type.create_by
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.create_by
     *
     * @param createBy the value for industry_type.create_by
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.create_date
     *
     * @return the value of industry_type.create_date
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.create_date
     *
     * @param createDate the value for industry_type.create_date
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.update_by
     *
     * @return the value of industry_type.update_by
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.update_by
     *
     * @param updateBy the value for industry_type.update_by
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.update_date
     *
     * @return the value of industry_type.update_date
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.update_date
     *
     * @param updateDate the value for industry_type.update_date
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.remarks
     *
     * @return the value of industry_type.remarks
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.remarks
     *
     * @param remarks the value for industry_type.remarks
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.del_flag
     *
     * @return the value of industry_type.del_flag
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.del_flag
     *
     * @param delFlag the value for industry_type.del_flag
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_type
     *
     * @mbg.generated Mon May 21 21:55:44 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", industryTypeName=").append(industryTypeName);
        sb.append(", createBy=").append(createBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", remarks=").append(remarks);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}