package com.create80.rd.modules.engineering.api.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EngineeringWorkOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.order_number
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.order_type
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.description
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.priority
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.status
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.enterprise_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.project_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.sponsor_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String sponsorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.assignor_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String assignorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.team_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.estimate_start_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private Date estimateStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.estimate_end_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private Date estimateEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.estimate_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private BigDecimal estimateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.accept_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private Date acceptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.actual_start_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private Date actualStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.actual_end_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private Date actualEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.actual_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private BigDecimal actualTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.insert_by
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String insertBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.insert_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.update_by
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.update_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.remarks
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.is_deleted
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.assignor_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private Date assignorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.sponsor_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private Date sponsorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineering_work_order.contract_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table engineering_work_order
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.id
     *
     * @return the value of engineering_work_order.id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.id
     *
     * @param id the value for engineering_work_order.id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.order_number
     *
     * @return the value of engineering_work_order.order_number
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.order_number
     *
     * @param orderNumber the value for engineering_work_order.order_number
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.order_type
     *
     * @return the value of engineering_work_order.order_type
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.order_type
     *
     * @param orderType the value for engineering_work_order.order_type
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.description
     *
     * @return the value of engineering_work_order.description
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.description
     *
     * @param description the value for engineering_work_order.description
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.priority
     *
     * @return the value of engineering_work_order.priority
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.priority
     *
     * @param priority the value for engineering_work_order.priority
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setPriority(String priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.status
     *
     * @return the value of engineering_work_order.status
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.status
     *
     * @param status the value for engineering_work_order.status
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.enterprise_id
     *
     * @return the value of engineering_work_order.enterprise_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.enterprise_id
     *
     * @param enterpriseId the value for engineering_work_order.enterprise_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.project_id
     *
     * @return the value of engineering_work_order.project_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.project_id
     *
     * @param projectId the value for engineering_work_order.project_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.sponsor_id
     *
     * @return the value of engineering_work_order.sponsor_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getSponsorId() {
        return sponsorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.sponsor_id
     *
     * @param sponsorId the value for engineering_work_order.sponsor_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setSponsorId(String sponsorId) {
        this.sponsorId = sponsorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.assignor_id
     *
     * @return the value of engineering_work_order.assignor_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getAssignorId() {
        return assignorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.assignor_id
     *
     * @param assignorId the value for engineering_work_order.assignor_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setAssignorId(String assignorId) {
        this.assignorId = assignorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.team_id
     *
     * @return the value of engineering_work_order.team_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.team_id
     *
     * @param teamId the value for engineering_work_order.team_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setTeamId(String teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.estimate_start_time
     *
     * @return the value of engineering_work_order.estimate_start_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public Date getEstimateStartTime() {
        return estimateStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.estimate_start_time
     *
     * @param estimateStartTime the value for engineering_work_order.estimate_start_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setEstimateStartTime(Date estimateStartTime) {
        this.estimateStartTime = estimateStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.estimate_end_time
     *
     * @return the value of engineering_work_order.estimate_end_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public Date getEstimateEndTime() {
        return estimateEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.estimate_end_time
     *
     * @param estimateEndTime the value for engineering_work_order.estimate_end_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setEstimateEndTime(Date estimateEndTime) {
        this.estimateEndTime = estimateEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.estimate_time
     *
     * @return the value of engineering_work_order.estimate_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public BigDecimal getEstimateTime() {
        return estimateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.estimate_time
     *
     * @param estimateTime the value for engineering_work_order.estimate_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setEstimateTime(BigDecimal estimateTime) {
        this.estimateTime = estimateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.accept_time
     *
     * @return the value of engineering_work_order.accept_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public Date getAcceptTime() {
        return acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.accept_time
     *
     * @param acceptTime the value for engineering_work_order.accept_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setAcceptTime(Date acceptTime) {
        this.acceptTime = acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.actual_start_time
     *
     * @return the value of engineering_work_order.actual_start_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public Date getActualStartTime() {
        return actualStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.actual_start_time
     *
     * @param actualStartTime the value for engineering_work_order.actual_start_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setActualStartTime(Date actualStartTime) {
        this.actualStartTime = actualStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.actual_end_time
     *
     * @return the value of engineering_work_order.actual_end_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public Date getActualEndTime() {
        return actualEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.actual_end_time
     *
     * @param actualEndTime the value for engineering_work_order.actual_end_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setActualEndTime(Date actualEndTime) {
        this.actualEndTime = actualEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.actual_time
     *
     * @return the value of engineering_work_order.actual_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public BigDecimal getActualTime() {
        return actualTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.actual_time
     *
     * @param actualTime the value for engineering_work_order.actual_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setActualTime(BigDecimal actualTime) {
        this.actualTime = actualTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.insert_by
     *
     * @return the value of engineering_work_order.insert_by
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getInsertBy() {
        return insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.insert_by
     *
     * @param insertBy the value for engineering_work_order.insert_by
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setInsertBy(String insertBy) {
        this.insertBy = insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.insert_time
     *
     * @return the value of engineering_work_order.insert_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.insert_time
     *
     * @param insertTime the value for engineering_work_order.insert_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.update_by
     *
     * @return the value of engineering_work_order.update_by
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.update_by
     *
     * @param updateBy the value for engineering_work_order.update_by
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.update_time
     *
     * @return the value of engineering_work_order.update_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.update_time
     *
     * @param updateTime the value for engineering_work_order.update_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.remarks
     *
     * @return the value of engineering_work_order.remarks
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.remarks
     *
     * @param remarks the value for engineering_work_order.remarks
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.is_deleted
     *
     * @return the value of engineering_work_order.is_deleted
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.is_deleted
     *
     * @param isDeleted the value for engineering_work_order.is_deleted
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.assignor_time
     *
     * @return the value of engineering_work_order.assignor_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public Date getAssignorTime() {
        return assignorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.assignor_time
     *
     * @param assignorTime the value for engineering_work_order.assignor_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setAssignorTime(Date assignorTime) {
        this.assignorTime = assignorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.sponsor_time
     *
     * @return the value of engineering_work_order.sponsor_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public Date getSponsorTime() {
        return sponsorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.sponsor_time
     *
     * @param sponsorTime the value for engineering_work_order.sponsor_time
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setSponsorTime(Date sponsorTime) {
        this.sponsorTime = sponsorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineering_work_order.contract_id
     *
     * @return the value of engineering_work_order.contract_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineering_work_order.contract_id
     *
     * @param contractId the value for engineering_work_order.contract_id
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineering_work_order
     *
     * @mbg.generated Fri Jun 22 11:15:23 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderNumber=").append(orderNumber);
        sb.append(", orderType=").append(orderType);
        sb.append(", description=").append(description);
        sb.append(", priority=").append(priority);
        sb.append(", status=").append(status);
        sb.append(", enterpriseId=").append(enterpriseId);
        sb.append(", projectId=").append(projectId);
        sb.append(", sponsorId=").append(sponsorId);
        sb.append(", assignorId=").append(assignorId);
        sb.append(", teamId=").append(teamId);
        sb.append(", estimateStartTime=").append(estimateStartTime);
        sb.append(", estimateEndTime=").append(estimateEndTime);
        sb.append(", estimateTime=").append(estimateTime);
        sb.append(", acceptTime=").append(acceptTime);
        sb.append(", actualStartTime=").append(actualStartTime);
        sb.append(", actualEndTime=").append(actualEndTime);
        sb.append(", actualTime=").append(actualTime);
        sb.append(", insertBy=").append(insertBy);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remarks=").append(remarks);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", assignorTime=").append(assignorTime);
        sb.append(", sponsorTime=").append(sponsorTime);
        sb.append(", contractId=").append(contractId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}