package com.create80.rd.modules.customer.enterprise.api.model;

import com.create80.rd.modules.customer.government.api.model.Contact;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Enterprise implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.id
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_name
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String enterpriseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.lat
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private BigDecimal lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.lng
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private BigDecimal lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.usc_code
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String uscCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.legal_person
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String legalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.registered_capital
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private BigDecimal registeredCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.registered_date
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private Date registeredDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.registered_address
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String registeredAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.registered_postcode
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private Integer registeredPostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.area_id
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.business_scope
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String businessScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.business_phone
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String businessPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.business_fax
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String businessFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.bank_account
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.bank_number
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String bankNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.bank_name
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.tax_number
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String taxNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.tax_phone
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String taxPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.recycling_type
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String recyclingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.status_type
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String statusType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.insert_by
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String insertBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.insert_time
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.update_by
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.update_time
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.remarks
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.is_deleted
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private String isDeleted;

    private List<Contact> contactList;

    private List<EnterpriseBusinessTypeRelation> enterpriseBusinessTypeRelationList;

    private List<EnterpriseIndustryTypeRelation> enterpriseIndustryTypeRelationList;

    private List<EnterprisePic> enterprisePicList;

    private List<EnterprisePollutionTypeRelation> enterprisePollutionTypeRelationList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.id
     *
     * @return the value of enterprise.id
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.id
     *
     * @param id the value for enterprise.id
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_name
     *
     * @return the value of enterprise.enterprise_name
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_name
     *
     * @param enterpriseName the value for enterprise.enterprise_name
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.lat
     *
     * @return the value of enterprise.lat
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.lat
     *
     * @param lat the value for enterprise.lat
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.lng
     *
     * @return the value of enterprise.lng
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public BigDecimal getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.lng
     *
     * @param lng the value for enterprise.lng
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setLng(BigDecimal lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.usc_code
     *
     * @return the value of enterprise.usc_code
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getUscCode() {
        return uscCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.usc_code
     *
     * @param uscCode the value for enterprise.usc_code
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setUscCode(String uscCode) {
        this.uscCode = uscCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.legal_person
     *
     * @return the value of enterprise.legal_person
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.legal_person
     *
     * @param legalPerson the value for enterprise.legal_person
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.registered_capital
     *
     * @return the value of enterprise.registered_capital
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public BigDecimal getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.registered_capital
     *
     * @param registeredCapital the value for enterprise.registered_capital
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setRegisteredCapital(BigDecimal registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.registered_date
     *
     * @return the value of enterprise.registered_date
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public Date getRegisteredDate() {
        return registeredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.registered_date
     *
     * @param registeredDate the value for enterprise.registered_date
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setRegisteredDate(Date registeredDate) {
        this.registeredDate = registeredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.registered_address
     *
     * @return the value of enterprise.registered_address
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getRegisteredAddress() {
        return registeredAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.registered_address
     *
     * @param registeredAddress the value for enterprise.registered_address
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setRegisteredAddress(String registeredAddress) {
        this.registeredAddress = registeredAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.registered_postcode
     *
     * @return the value of enterprise.registered_postcode
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public Integer getRegisteredPostcode() {
        return registeredPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.registered_postcode
     *
     * @param registeredPostcode the value for enterprise.registered_postcode
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setRegisteredPostcode(Integer registeredPostcode) {
        this.registeredPostcode = registeredPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.area_id
     *
     * @return the value of enterprise.area_id
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.area_id
     *
     * @param areaId the value for enterprise.area_id
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.business_scope
     *
     * @return the value of enterprise.business_scope
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.business_scope
     *
     * @param businessScope the value for enterprise.business_scope
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.business_phone
     *
     * @return the value of enterprise.business_phone
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getBusinessPhone() {
        return businessPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.business_phone
     *
     * @param businessPhone the value for enterprise.business_phone
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setBusinessPhone(String businessPhone) {
        this.businessPhone = businessPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.business_fax
     *
     * @return the value of enterprise.business_fax
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getBusinessFax() {
        return businessFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.business_fax
     *
     * @param businessFax the value for enterprise.business_fax
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setBusinessFax(String businessFax) {
        this.businessFax = businessFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.bank_account
     *
     * @return the value of enterprise.bank_account
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.bank_account
     *
     * @param bankAccount the value for enterprise.bank_account
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.bank_number
     *
     * @return the value of enterprise.bank_number
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getBankNumber() {
        return bankNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.bank_number
     *
     * @param bankNumber the value for enterprise.bank_number
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setBankNumber(String bankNumber) {
        this.bankNumber = bankNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.bank_name
     *
     * @return the value of enterprise.bank_name
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.bank_name
     *
     * @param bankName the value for enterprise.bank_name
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.tax_number
     *
     * @return the value of enterprise.tax_number
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getTaxNumber() {
        return taxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.tax_number
     *
     * @param taxNumber the value for enterprise.tax_number
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setTaxNumber(String taxNumber) {
        this.taxNumber = taxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.tax_phone
     *
     * @return the value of enterprise.tax_phone
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getTaxPhone() {
        return taxPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.tax_phone
     *
     * @param taxPhone the value for enterprise.tax_phone
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setTaxPhone(String taxPhone) {
        this.taxPhone = taxPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.recycling_type
     *
     * @return the value of enterprise.recycling_type
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getRecyclingType() {
        return recyclingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.recycling_type
     *
     * @param recyclingType the value for enterprise.recycling_type
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setRecyclingType(String recyclingType) {
        this.recyclingType = recyclingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.status_type
     *
     * @return the value of enterprise.status_type
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getStatusType() {
        return statusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.status_type
     *
     * @param statusType the value for enterprise.status_type
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setStatusType(String statusType) {
        this.statusType = statusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.insert_by
     *
     * @return the value of enterprise.insert_by
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getInsertBy() {
        return insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.insert_by
     *
     * @param insertBy the value for enterprise.insert_by
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setInsertBy(String insertBy) {
        this.insertBy = insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.insert_time
     *
     * @return the value of enterprise.insert_time
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.insert_time
     *
     * @param insertTime the value for enterprise.insert_time
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.update_by
     *
     * @return the value of enterprise.update_by
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.update_by
     *
     * @param updateBy the value for enterprise.update_by
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.update_time
     *
     * @return the value of enterprise.update_time
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.update_time
     *
     * @param updateTime the value for enterprise.update_time
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.remarks
     *
     * @return the value of enterprise.remarks
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.remarks
     *
     * @param remarks the value for enterprise.remarks
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.is_deleted
     *
     * @return the value of enterprise.is_deleted
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.is_deleted
     *
     * @param isDeleted the value for enterprise.is_deleted
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    public List<Contact> getContactList() {
        return contactList;
    }

    public void setContactList(List<Contact> contactList) {
        this.contactList=contactList;
    }

    public List<EnterpriseBusinessTypeRelation> getEnterpriseBusinessTypeRelationList() {
        return enterpriseBusinessTypeRelationList;
    }

    public void setEnterpriseBusinessTypeRelationList(List<EnterpriseBusinessTypeRelation> enterpriseBusinessTypeRelationList) {
        this.enterpriseBusinessTypeRelationList=enterpriseBusinessTypeRelationList;
    }

    public List<EnterpriseIndustryTypeRelation> getEnterpriseIndustryTypeRelationList() {
        return enterpriseIndustryTypeRelationList;
    }

    public void setEnterpriseIndustryTypeRelationList(List<EnterpriseIndustryTypeRelation> enterpriseIndustryTypeRelationList) {
        this.enterpriseIndustryTypeRelationList=enterpriseIndustryTypeRelationList;
    }

    public List<EnterprisePic> getEnterprisePicList() {
        return enterprisePicList;
    }

    public void setEnterprisePicList(List<EnterprisePic> enterprisePicList) {
        this.enterprisePicList=enterprisePicList;
    }

    public List<EnterprisePollutionTypeRelation> getEnterprisePollutionTypeRelationList() {
        return enterprisePollutionTypeRelationList;
    }

    public void setEnterprisePollutionTypeRelationList(List<EnterprisePollutionTypeRelation> enterprisePollutionTypeRelationList) {
        this.enterprisePollutionTypeRelationList=enterprisePollutionTypeRelationList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbg.generated Wed Jun 20 14:06:26 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", enterpriseName=").append(enterpriseName);
        sb.append(", lat=").append(lat);
        sb.append(", lng=").append(lng);
        sb.append(", uscCode=").append(uscCode);
        sb.append(", legalPerson=").append(legalPerson);
        sb.append(", registeredCapital=").append(registeredCapital);
        sb.append(", registeredDate=").append(registeredDate);
        sb.append(", registeredAddress=").append(registeredAddress);
        sb.append(", registeredPostcode=").append(registeredPostcode);
        sb.append(", areaId=").append(areaId);
        sb.append(", businessScope=").append(businessScope);
        sb.append(", businessPhone=").append(businessPhone);
        sb.append(", businessFax=").append(businessFax);
        sb.append(", bankAccount=").append(bankAccount);
        sb.append(", bankNumber=").append(bankNumber);
        sb.append(", bankName=").append(bankName);
        sb.append(", taxNumber=").append(taxNumber);
        sb.append(", taxPhone=").append(taxPhone);
        sb.append(", recyclingType=").append(recyclingType);
        sb.append(", statusType=").append(statusType);
        sb.append(", insertBy=").append(insertBy);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remarks=").append(remarks);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", contactList=").append(contactList);
        sb.append(", enterpriseBusinessTypeRelationList=").append(enterpriseBusinessTypeRelationList);
        sb.append(", enterpriseIndustryTypeRelationList=").append(enterpriseIndustryTypeRelationList);
        sb.append(", enterprisePicList=").append(enterprisePicList);
        sb.append(", enterprisePollutionTypeRelationList=").append(enterprisePollutionTypeRelationList);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}