package com.knt.rd.modules.customer.government.api.model;

import java.io.Serializable;
import java.util.Date;

public class Contact implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.id
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.customer_type
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private String customerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.customer_id
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.name
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.title
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.phone
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.email
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.create_by
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.create_date
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.update_by
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.update_date
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.remarks
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.del_flag
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contact
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.id
     *
     * @return the value of contact.id
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.id
     *
     * @param id the value for contact.id
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.customer_type
     *
     * @return the value of contact.customer_type
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.customer_type
     *
     * @param customerType the value for contact.customer_type
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.customer_id
     *
     * @return the value of contact.customer_id
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.customer_id
     *
     * @param customerId the value for contact.customer_id
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.name
     *
     * @return the value of contact.name
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.name
     *
     * @param name the value for contact.name
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.title
     *
     * @return the value of contact.title
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.title
     *
     * @param title the value for contact.title
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.phone
     *
     * @return the value of contact.phone
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.phone
     *
     * @param phone the value for contact.phone
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.email
     *
     * @return the value of contact.email
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.email
     *
     * @param email the value for contact.email
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.create_by
     *
     * @return the value of contact.create_by
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.create_by
     *
     * @param createBy the value for contact.create_by
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.create_date
     *
     * @return the value of contact.create_date
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.create_date
     *
     * @param createDate the value for contact.create_date
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.update_by
     *
     * @return the value of contact.update_by
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.update_by
     *
     * @param updateBy the value for contact.update_by
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.update_date
     *
     * @return the value of contact.update_date
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.update_date
     *
     * @param updateDate the value for contact.update_date
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.remarks
     *
     * @return the value of contact.remarks
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.remarks
     *
     * @param remarks the value for contact.remarks
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.del_flag
     *
     * @return the value of contact.del_flag
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.del_flag
     *
     * @param delFlag the value for contact.del_flag
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Mon May 21 21:32:03 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", customerType=").append(customerType);
        sb.append(", customerId=").append(customerId);
        sb.append(", name=").append(name);
        sb.append(", title=").append(title);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", createBy=").append(createBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", remarks=").append(remarks);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}